const disabledPdfElements = [
    'toolbarGroup-View',
    'toolbarGroup-Edit',
    'toolbarGroup-Annotate',
    'toolbarGroup-Shapes',
    'toolbarGroup-Insert',
    'toolbarGroup-Forms',
    'toolbarGroup-FillAndSign',
    'downloadButton',
    'saveAsButton',
    'printButton',
    'settingsKeyboardButton',
    'settingsAdvancedButton',
    'panToolButton',
    'selectToolButton',
    'fullScreenButton',
    'thumbDelete',
    'thumbRotateClockwise',
    'pageManipulationOverlayButton',
    'pageAdditionalControlsHeader',
    'thumbnailsControlManipulatePopupTrigger',
    'thumbnailsControlManipulatePopupSmallTrigger',
    'thumbnailsControlRotatePopupTrigger',
    'documentControl',
    'thumbnailsControlRotateCounterClockwise',
    'thumbnailsControlRotateClockwise',
    'thumbnailsControlInsert',
    'thumbnailsControlReplace',
    'thumbnailsControlExtract',
    'thumbnailsControlDelete',
    'moveToTop',
    'moveToBottom',
    'thumbnailsPanel',
    'coverLayoutButton',
    'toggleCompareModeButton',
    'freeTextToolButton',
    'markInsertTextToolButton',
    'markReplaceTextToolButton',
    'highlightToolButton',
    // 'stickyToolButton',
    'freeHandToolButton',
    'freeHandHighlightToolButton',
    'linkButton',
    'toolsHeader',


]

export default disabledPdfElements;